development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://olyuturvvrekjj:3473c4d18fb96016e6f3099766415a4ecd1d8590cdd3de181843d77a95764bd5@ec2-23-23-111-171.compute-1.amazonaws.com:5432/d7j48pakhcquvv
  #channel_prefix: rails5App_production
